# Generated by Django 5.0.7 on 2024-07-24 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('statecode', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('englishname', models.CharField(blank=True, max_length=300, null=True)),
                ('localname', models.CharField(blank=True, max_length=300, null=True)),
                ('statecreated', models.DateTimeField(auto_now_add=True, null=True)),
                ('stateupdated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('districtcode', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('englishname', models.CharField(blank=True, max_length=200, null=True)),
                ('localname', models.CharField(blank=True, max_length=200, null=True)),
                ('districtcreated', models.DateTimeField(auto_now_add=True, null=True)),
                ('districtupdated', models.DateTimeField(auto_now=True, null=True)),
                ('state', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='FETCH.state')),
            ],
        ),
        migrations.CreateModel(
            name='Subdistrict',
            fields=[
                ('subdistrictcode', models.IntegerField(default=2, primary_key=True, serialize=False)),
                ('englishname', models.CharField(blank=True, max_length=200, null=True)),
                ('localname', models.CharField(blank=True, max_length=200, null=True)),
                ('subdistrictcreated', models.DateTimeField(auto_now_add=True, null=True)),
                ('subdistrictupdated', models.DateTimeField(auto_now=True, null=True)),
                ('district', models.ForeignKey(blank=True, default=1121, null=True, on_delete=django.db.models.deletion.CASCADE, to='FETCH.district')),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('villagecode', models.IntegerField(default=3, primary_key=tuple, serialize=False)),
                ('englishname', models.CharField(blank=True, max_length=200, null=True)),
                ('localname', models.CharField(blank=True, max_length=200, null=True)),
                ('vilagecreated', models.DateTimeField(auto_now_add=True, null=True)),
                ('villageupdated', models.DateTimeField(auto_now=True, null=True)),
                ('subdistrict', models.ForeignKey(blank=True, default=12342, null=True, on_delete=django.db.models.deletion.CASCADE, to='FETCH.subdistrict')),
            ],
        ),
    ]
