# Generated by Django 4.2.14 on 2024-07-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FETCH', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agriculturaldata',
            name='maxfile',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
