# Generated by Django 4.2.14 on 2024-07-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FETCH', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdistrict',
            name='state',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
