# Generated by Django 4.2.14 on 2024-07-31 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FETCH', '0002_agriculturaldata_maxfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropdata',
            name='district',
            field=models.ForeignKey(blank=True, default=480, null=True, on_delete=django.db.models.deletion.CASCADE, to='FETCH.district'),
        ),
        migrations.AddField(
            model_name='cropdata',
            name='state',
            field=models.ForeignKey(blank=True, default=27, null=True, on_delete=django.db.models.deletion.CASCADE, to='FETCH.state'),
        ),
    ]
