# Generated by Django 4.2.14 on 2024-07-31 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FETCH', '0003_cropdata_district_cropdata_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropdata',
            name='subdistrict',
            field=models.ForeignKey(blank=True, default=3648, null=True, on_delete=django.db.models.deletion.CASCADE, to='FETCH.subdistrict'),
        ),
    ]
