# Generated by Django 4.2.14 on 2024-07-24 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FETCH', '0003_village_district_village_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='village',
            name='district',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='FETCH.district'),
        ),
        migrations.AlterField(
            model_name='village',
            name='state',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='FETCH.state'),
        ),
    ]
