# Generated by Django 4.2.14 on 2024-08-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FETCH', '0005_cropdatajson_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropdatajson',
            name='district',
            field=models.CharField(blank=True, default=None, null=True),
        ),
    ]
