# Generated by Django 4.2.14 on 2024-07-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FETCH', '0005_alter_village_district_alter_village_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='village',
            old_name='vilagecreated',
            new_name='villagecreated',
        ),
        migrations.AlterField(
            model_name='village',
            name='district',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='village',
            name='state',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='village',
            name='villagecode',
            field=models.IntegerField(default=3, primary_key=True, serialize=False),
        ),
    ]
