# Generated by Django 4.2.14 on 2024-07-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FETCH', '0007_alter_village_district_alter_village_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cropname', models.CharField(max_length=200)),
            ],
        ),
    ]
